apiVersion: opa.k8smgmt.io/v3
kind: OPAPolicy
metadata:
  name: bp-psp-restricted
  project: defaultproject
spec:
  constraintList:
  - name: allow-privilege-escalation-container-custom 
    version: v1
  - name: allowed-users-custom         
    version: v1  
  - name: app-armor-custom  
    version: v1  
  - name: flex-volumes-custom
    version: v1  
  - name: forbidden-sysctls-custom
    version: v1  
  - name: host-filesystem-custom   
    version: v1  
  - name: host-namespace-custom     
    version: v1  
  - name: host-network-ports-custom 
    version: v1  
  - name: linux-capabilities-custom 
    version: v1  
  - name: privileged-container-custom 
    version: v1  
  - name: proc-mount-custom   
    version: v1  
  - name: read-only-root-filesystem-custom   
    version: v1  
  - name: se-linux-custom       
    version: v1  
  - name: seccomp-custom   
    version: v1  
  - name: volume-types-custom
    version: v1
  sharing:
    enabled: true
    projects:
    - name: defaultproject
  version: v1