apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Privileged-Container
metadata:
  name: privileged-container
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces: ["kube-system"]
