apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: read-only-root-filesystem-custom
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/read-only-root-filesystem-custom/read-only-root-filesystem.yaml
    options: {}
    type: Yaml

