apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Read-Only-Root-Filesystem
metadata:
  name: read-only-root-filesystem
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
