apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: block-nodeport-services-custom
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/block-nodeport-services-custom/block-nodeport-services.yaml
    options: {}
    type: Yaml
  published: true 
  templateName: block-nodeport-services-custom
  version: v1