apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: linux-capabilities-custom
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/linux-capabilities-custom/linux-capabilities.yaml
    options: {}
    type: Yaml
  published: true 
  templateName: linux-capabilities-custom
  version: v1