apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Proc-Mount
metadata:
  name: proc-mount
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    procMount: Default
