apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Allow-Privilege-Escalation-Container
metadata:
  name: allow-privilege-escalation-container
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
