apiVersion: constraints.gatekeeper.sh/v1beta1
kind: SE-Linux
metadata:
  name: se-linux
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedSELinuxOptions:
      - level: s0:c123,c456
        role: object_r
        type: svirt_sandbox_file_t
        user: system_u
