kind: Cluster
metadata:
  name: cloudwatch-cluster
  project: defaultproject
spec:
  blueprint: cloudwatch-blueprint
  blueprintversion: v1
  cloudprovider: aws-cloud-credential
  cniprovider: aws-cni
  type: eks
---
apiVersion: rafay.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cloudwatch-cluster
  region: us-west-1
  tags:
  version: "1.21"
managedNodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 2
    iam:
     withAddonPolicies:
      albIngress: true
      autoScaler: true
      efs: true
      cloudWatch: true