apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: karpenter-cluster
  project: defaultproject
spec:
  blueprintConfig:
    name: minimal
    version: latest
  cloudCredentials: aws-cloud-credential
  config:
    iam:
      withOIDC: true
      serviceAccounts:
      - attachPolicy:
          Statement:
          - Action:
            # Write Operations
            - "ec2:CreateLaunchTemplate"
            - "ec2:CreateFleet"
            - "ec2:RunInstances"
            - "ec2:CreateTags"
            - "iam:PassRole"
            - "ec2:TerminateInstances"
            # Read Operations
            - "ec2:DescribeLaunchTemplates"
            - "ec2:DescribeInstances"
            - "ec2:DescribeSecurityGroups"
            - "ec2:DescribeSubnets"
            - "ec2:DescribeInstanceTypes"
            - "ec2:DescribeInstanceTypeOfferings"
            - "ec2:DescribeAvailabilityZones"
            - "ssm:GetParameter"
            - "eks:DescribeCluster"
            Effect: Allow
            Resource: "*"
          Version: "2012-10-17"
        metadata:
          name: karpenter
          namespace: karpenter  
    identityMappings:
      arns:
      - arn: "arn:aws:iam::<ACCOUNT-NUMBER>:role/KarpenterNodeRole-Rafay"
        username: system:node:{{EC2PrivateDNSName}}
        group:
        - system:bootstrappers
        - system:nodes	  
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      instanceTypes:
      - t3.medium
      - t3.large
      maxSize: 4
      minSize: 2
      name: managed-spot
      spot: true
    - amiFamily: AmazonLinux2
      desiredCapacity: 1
      instanceType: t3.large
      labels:
        nodes: system
      maxSize: 2
      minSize: 1
      name: managed-system
      taints:
      - effect: NoSchedule
        key: components
        value: system
    metadata:
      name: karpenter-cluster
      region: us-west-2
      tags:
        'cluster-name': 'karpenter-cluster'
        email: tim@rafay.co
        env: qa
      version: "1.23"
    network:
      cni:
        name: aws-cni
    vpc:
      autoAllocateIPv6: false
      clusterEndpoints:
        privateAccess: true
        publicAccess: false
      cidr: 192.168.0.0/16
  systemComponentsPlacement:
    nodeSelector:
      nodes: system
    tolerations:
    - effect: NoSchedule
      key: components
      operator: Equal
      value: system
  type: aws-eks
