apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Forbidden-Sysctls
metadata:
  name: forbidden-sysctls
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    forbiddenSysctls:
    # - "*" # * may be used to forbid all sysctls
    - kernel.*
