apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gpu-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            nvidia.com/gpu: 1  # Requesting 1 GPU
        ports:
        - containerPort: 80
