kind: FleetPlan
apiVersion: infra.k8smgmt.io/v3
metadata:
  name: eks-fleet1-plan-1-24
  project: defaultproject
spec:
  fleet:
    kind: clusters
    labels:
      rafay.dev/clusterType: aws-eks
      rafay.dev/k8sVersion: '1.24'
    projects:
      - name: defaultproject
  operationWorkflow:
    operations:
      - name: eks-1-24-plan
        prehooks:
          - name: deprecated-api-check
            description: Deprecated APIs Check
            inject:
              - KUBECONFIG
            containerConfig:
              runner:
                type: cluster
              image: ghcr.io/doitintl/kube-no-trouble:latest
              arguments:
                - '-o'
                - json
                - '-e'
              cpuLimitMilli: '4'
              memoryLimitMb: '100'
            timeoutSeconds: 60
          - name: pre-upgrade-checker
            description: >-
              deprecated API's and will verify the current context against
              v1.25.13 version
            inject:
              - KUBECONFIG
            containerConfig:
              runner:
                type: cluster
              image: ctadeu/kubepug:latest
              arguments:
                - '--k8s-version=v1.25.13'
              cpuLimitMilli: '4'
              memoryLimitMb: '100'
            timeoutSeconds: 60
          - name: check-aws-load-balancer
            description: ''
            inject:
              - KUBECONFIG
            containerConfig:
              runner:
                type: cluster
              image: >-
                registry.rafay-edge.net/rafay/check-aws-load-balancer-controller:v1
              arguments:
                - aws-load-balancer-controller-name       # This is the AWS Load Balancer Controller deployment name 
                - aws-namespace                           # This is the namespace of AWS Load Balancer Controller deployment
              cpuLimitMilli: '4'
              memoryLimitMb: '100'
            timeoutSeconds: 60
        action:
          type: nodeGroupsAndControlPlaneUpgrade
          description: upgrade to 1.25
          name: eks-cluster-upgrade
          nodeGroupsAndControlPlaneUpgradeConfig:
            version: '1.25'