kind: FleetPlan
apiVersion: infra.k8smgmt.io/v3
metadata:
  name: eks-fleet1-plan-1-23
  project: defaultproject
spec:
  fleet:
    kind: clusters
    labels:
      rafay.dev/clusterType: aws-eks
      rafay.dev/k8sVersion: '1.23'
    projects:
      - name: defaultproject
  operationWorkflow:
    operations:
      - name: eks-1-23-plan
        prehooks:
          - name: deprecated-api-check
            description: Deprecated APIs Check
            inject:
              - KUBECONFIG
            containerConfig:
              runner:
                type: cluster
              image: ghcr.io/doitintl/kube-no-trouble:latest
              arguments:
                - '-o'
                - json
                - '-e'
              cpuLimitMilli: '4'
              memoryLimitMb: '100'
            timeoutSeconds: 60
          - name: pre-upgrade-checker
            description: >-
              deprecated API's and will verify the current context against
              v1.24.15  version
            inject:
              - KUBECONFIG
            containerConfig:
              runner:
                type: cluster
              image: ctadeu/kubepug:latest
              arguments:
                - '--k8s-version=v1.24.15'
              cpuLimitMilli: '4'
              memoryLimitMb: '100'
            timeoutSeconds: 60
          - name: docker-socket-detector-check
            description: ''
            inject:
              - KUBECONFIG
            containerConfig:
              runner:
                type: cluster
              image: registry.rafay-edge.net/rafay/dockersocketdetector:v1
              arguments:
                - '-e'
              cpuLimitMilli: '4'
              memoryLimitMb: '100'
            timeoutSeconds: 100
        action:
          type: nodeGroupsAndControlPlaneUpgrade
          description: upgrade to 1.24
          name: eks-cluster-upgrade
          nodeGroupsAndControlPlaneUpgradeConfig:
            version: '1.24'