apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Host-Filesystem
metadata:
  name: host-filesystem
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    allowedHostPaths:
    - readOnly: true
      pathPrefix: "/foo"
